### ISSUE TITLE
Milestone 3 Juno & Kera

### ISSUE THREAD

**Issue by huijuechen** [UBC-MDS/ellognea-ptung-mental-health#32]
Feedback from [Juno Chen](https://github.com/huijuechen) and [Kera Yucel](https://github.com/K3ra-y).
Nice colour scheme, layout looks clean, liked the data description tab a lot, very helpful.

- [ ] Add stacked bars to the graphs, for separating age groups.
- [ ] Update the y-axis labels from count to percentage
- [x] Make the size of the bars consistent even there is no data for a particular category

Great job on first milestone.

**Comment by ellognea** [comment]
Thanks for the feedback. We've made the width of the bars consistent.
