### ISSUE TITLE
Feedback milestone 2

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/ellognea-ptung-mental-health#35]
Great!

Suggestions for improvement:
- [x] Nice that you are including the variable descriptions!
    - It would be helpful to have these as [tooltips in the datatable](https://stackoverflow.com/questions/31124122/r-shiny-mouseover-text-for-table-columns).
- [x] Instead of repeating the same code over and over again for the barplots, use facetting with ggplot.
    - This would also allow you to easily fix the ymax as the same value for all pots which facilitates comparisons between questions. It would also allow for just using one legend for all plots which will reduce clutter.
- [x] You can be more generous with comments from around line 60.
-  [x] It's unexpected that clicking country or age pops up a new box with the filters underneath the radio buttons. I think it would be more intuitive either if this box popped up just under the checked check box, or if you skipped the checkboxes altogether and just had the `selectInput` boxes (the default could then be a meta tag called "All" or similar). The first approach might be the most time efficient for you.
- [x] It is could be confusing that the `Country` and `Age` filters apply to both the Graphics and Data view panes, while the Subgruop radio buttons only filters the questions displayed in the Graphics pane. Consider making this clearer, either by separating the side panel and clearly indicating this difference or use a nested pane within the graphics pane to distinguish between "Personal" and "Professional" (like so https://stackoverflow.com/questions/22206290/r-shiny-making-sub-panels).
- [x] I don't think the titles should include the "vs Treatment" part. You are not really plotting one variable versus another (that is often a scatter plot). You are looking at the counts for one variable (e.g. gender) while grouping/stratifying by another (treatment).
-  [x] Can you make the treatment legend label be closer to the legend indicators for "Yes" and "No", it is currently floating in the air a bit above.

**Comment by tungpatrick** [comment]
Thank you Joel! However, I do have a little bit of confusion on some feedback. I'm not really sure what a tooltip is. I went to the link you have sent and basically only created a "container", which is almost identical to what it originally looked like, which is why I do not believe that I am understanding this correctly. Please advise. 

Also, would you happen to know how we could change the legend positions using `ggplotly`. Legend layouts cannot be done in `ggplotly` the same way as `ggplot`. I managed to move the legend, but the title of the legend does not move with it.

**Comment by ellognea** [comment]
"Instead of repeating the same code over and over again for the barplots, use facetting with ggplot.
This would also allow you to easily fix the ymax as the same value for all pots which facilitates comparisons between questions. It would also allow for just using one legend for all plots which will reduce clutter"

- Question:  I understand that faceting is used to show different subset of the data after fixing X and Y . In our case Y is fixed but X varies from plot to plot. 
Could you please provide an example of how faceting can be used ? 

Thank you !

**Comment by joelostblom** [comment]
@tungpatrick  Yes, for the tooltips I am referring to adding hover text to the DataTable columns names, so that the user can see directly what those variables are instead of switching tabs. This is a suggestion for an addition that would be a nice touch and you are by no means required to make this change. It is up to you to determine if you think it will be a worthwhile addition to your app given the benefit it might bring and the time it takes to implement (you might have other things you prefer to work on).

For the legend, look into the legend options mentioned [here](https://plot.ly/r/reference/#layout-legend), `valign` looks promising, you could also try changing `orientation` or one of the parameters relating to the y-pos. [This](https://github.com/ropensci/plotly/issues/1049#issuecomment-329778236) and other comments in the same issue could be helpful.

@ellognea  As you mentioned, facetting is used to show subsets of the data in separate subplots. It doesn't really matter what your initial data frame looks like since you can reshape it to whatever you want using `gather` and `spread` (have you covered these in class?).

In this case you want to create a long data frame using `gather` where you collect all four variables/columns you want to display in the same plot under the same column name (e.g. 'variable') in the data frame and all their values in another columns (e.g. 'value'). Then you count the values the same way you have done now and facet based on the column that holds all the variable names. You set the scales so that x is free but y is fixed. See [this SO answer](https://stackoverflow.com/a/34811062) for how to change the subplot titles from the variable names to whatever you want. Using this approach, I created a plot that looks like this

![image](https://user-images.githubusercontent.com/4560057/51761827-ee751a80-2082-11e9-8b72-4b96a57ea811.png)

You can use the theming to change it into whatever you think suits your app appearance.

Do these elaborations make it clearer for you what I mean?

**Comment by ellognea** [comment]
Very helpful ! Thanks a lot Joel !
